# Generated by Django 2.2.4 on 2019-08-24 16:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(max_length=255, null=True, upload_to=accounts.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='county',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
