# Generated by Django 2.2.4 on 2019-08-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190826_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
