# Generated by Django 2.2.4 on 2019-08-27 07:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190826_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(max_length=255, null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
