# Generated by Django 2.2.4 on 2019-08-27 10:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190827_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, height_field='None', null=True, upload_to=accounts.models.user_directory_path, width_field='None'),
        ),
    ]
