# Generated by Django 2.2.4 on 2019-08-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190828_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verify_email',
        ),
    ]
