# Generated by Django 2.2.4 on 2019-09-16 09:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190911_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='placeholder/default.png', max_length=255, null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
