# Generated by Django 2.2.4 on 2019-09-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190916_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(help_text='Required. Min 10 characters', max_length=5000, null=True),
        ),
    ]
