# Generated by Django 2.2.4 on 2019-09-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20190917_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(help_text='Required. Min 10 characters', null=True),
        ),
    ]
