# Generated by Django 2.2.4 on 2019-09-23 09:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20190923_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_height',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_width',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='placeholder/default.png', height_field='avatar_height', max_length=255, null=True, upload_to=accounts.models.user_directory_path, verbose_name={'rotations': None}, width_field='avatar_width'),
        ),
    ]
