# Generated by Django 2.2.4 on 2019-09-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20190923_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo_height',
            new_name='avatar_height',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='photo_width',
            new_name='avatar_width',
        ),
    ]
