# Generated by Django 2.2.4 on 2019-09-23 09:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20190923_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='placeholder/default.png', height_field='avatar_height', max_length=255, null=True, upload_to=accounts.models.user_directory_path, width_field='avatar_width'),
        ),
    ]
