# Generated by Django 2.2.4 on 2019-09-25 15:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20190923_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_crop',
            field=models.ImageField(blank=True, default='', height_field='avatar__crop_height', max_length=255, null=True, upload_to=accounts.models.user_directory_path, width_field='avatar_crop_width'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_crop_height',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_crop_width',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
