# Generated by Django 2.2.4 on 2019-09-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20190926_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file',
            field=models.ImageField(default='na', upload_to=''),
            preserve_default=False,
        ),
    ]
