# Generated by Django 2.2.4 on 2019-09-27 09:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20190927_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_width',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='file',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='placeholder/default.png', max_length=255, null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
